{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-status.fullname" . }}-clusterrole
  labels:
    {{- include "kube-status.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["kafka.strimzi.io"]
  resources: ["kafkaconnectors", "kafkaconnectors/status"]
  verbs: ["get", "watch", "list", "patch", "update"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications", "sparkapplications/status"]
  verbs: ["get", "watch", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-status.fullname" . }}-global
  labels:
    {{- include "kube-status.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "kube-status.serviceAccountName" . }}
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kube-status.fullname" . }}-clusterrole
  apiGroup: ""
---
{{- end }}
