apiVersion: v1
kind: Secret
metadata:
  name: azure-ad
type: Opaque
stringData:
  AzureAd__Domain: {{ $.Values.azureAd.domain | quote }}
  AzureAd__TenantId: {{ $.Values.azureAd.tenantId | quote }}
  AzureAd__ClientId: {{ $.Values.azureAd.clientId | quote }}
  AzureAd__ClientSecret: {{ $.Values.azureAd.clientSecret | quote }}
  AzureAd__Audience: {{ $.Values.azureAd.audience | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-ad-job
type: Opaque
stringData:
  CLIENT_ID: {{ $.Values.azureAd.clientId | quote }}
  CLIENT_SECRET: {{ $.Values.azureAd.clientSecret | quote }}
  GRANT_TYPE: "client_credentials"
  SCOPE: {{ printf "%s/.default" $.Values.azureAd.clientId | quote }}
  TENANT_ID: {{ $.Values.azureAd.tenantId | quote }}
