{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-status.serviceAccountName" . }}
  labels:
    {{- include "kube-status.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-account
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
