{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "kube-status.fullname" . }}
  labels:
    {{- include "kube-status.labels" . | nindent 4 }}
    app.kubernetes.io/component: virtual-service
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - name: metrics-redirect
      match:
        - uri:
            exact: /metrics
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "kube-status.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
    - name: {{ include "kube-status.fullname" . }}
      route:
        - destination:
            host: {{ include "kube-status.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
{{- end -}}
