name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
      - "feature/**"

    paths-ignore:
      - "**.md"
      - ".github/**"
      - "helm/**"

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: redsailtechnologies/kube-status

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --target release --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_ID=docker.io/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          [[ "$VERSION" =~ ^"feature/".* ]] && VERSION=$(echo $VERSION | sed -e 's|/|-|g')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
        working-directory: ./src
